version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: freshbox-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: FreshBox
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
